# GAME : 'CartPole-v1'
GAME : 'Acrobot-v1'

HIDDEN_LAYERS : [16, 16]

BATCH_SIZE: 64
MEMORY_CAPACITY: 10000
MAX_STEPS: 200
MAX_EPISODES: 1000

GAMMA: 0.99
TARGET_UPDATE: 4
TAU: 0.5
LEARNING_RATE: 0.001
GAMMA_LR: 0.9
STEP_LR: 2000

# Exploration settings
EPSILON_START: 0.2
EPSILON_END: 0.05
EPSILON_DECAY: 500

# Use double DQN
DOUBLE_DQN : False

# Use N-steps return (1 to not use)
N_STEP : 1

GRAD_CLAMPING : False
FREQ_PLOT : 25
FREQ_EVAL : 25
FREQ_SAVE : 250
