
# GAME : "Pendulum-v0"
# GAME : "LunarLanderContinuous-v2"
# GAME : "BipedalWalker-v2"
GAME : {id: Hypercube-v0,
        n_dimensions: 1,
        acceleration: False}

HIDDEN_VALUE_LAYERS : [32, 32, 32]
HIDDEN_Q_LAYERS : [32, 32, 32]
HIDDEN_PI_LAYERS : [32, 32]

MEMORY_CAPACITY : 1000000
BATCH_SIZE : 100
GAMMA : 0.99
VALUE_LR : 0.001
SOFTQ_LR : 0.001
ACTOR_LR : 0.001

TAU : 0.005

AUTO_ALPHA : True
ALPHA_LR : 0.001

MAX_EPISODES : 10000
MAX_STEPS : 50  # Max steps per episode

FREQ_PLOT : 10
FREQ_EVAL : 25
FREQ_SAVE : 250
