
GAME : "LunarLanderContinuous-v2"

HIDDEN_LAYERS : [400, 300]

MEMORY_CAPACITY : 10000000
BATCH_SIZE : 64
GAMMA : 0.99
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001
TAU : 0.005

EXPLO_SIGMA : 0.1  # Exploration noise
UPDATE_SIGMA : 0.2
UPDATE_CLIP : 0.5

MAX_EPISODES : 3000
MAX_STEPS : 50000

FREQ_PLOT : 25
FREQ_EVAL : 25
FREQ_SAVE : 250
